name: idkit_assets
description: This package is a multi-functional command-line toolkit for managing Flutter project resource files. The package is easy to use and has strong stability.
version: 1.1.0
homepage: https://github.com/zhoushuangjian001/idkit_assets

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  io: ^1.0.3
  path: ^1.8.1

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0

executables:
  idkit_assets: idkit_assets
