name: idkit_assets
description: Flutter project resource management command tool.
version: 1.0.0
homepage: https://github.com/zhoushuangjian001/idkit_assets

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  io: ^1.0.3
  path: ^1.8.1

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0

executables:
  idkit_assets: idkit_assets
